version: '2'
services:
  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
      - 21222:21222
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mounts/traefik.toml:/traefik.toml
      - ./mounts/acme.json:/acme.json
    container_name: traefik

networks:
  web:
    external: true
